# --- DataSource configuration ---
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=sqluser
quarkus.datasource.password=sqluserpw
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/login_
quarkus.http.root-path=/login
quarkus.http.static-resources.index-page=index.html